# Dependencies
markdown:            redcarpet
highlighter:         pygments

# Permalinks
#
# Use of `relative_permalinks` ensures post links from the index work properly.
permalink:           pretty
relative_permalinks: true

# Setup
title:               scott's
tagline:             'beer recipes'
description:         'my beer recipes'
baseurl:             /
paginate:            3

# About/contact
author:
  name:              Scott Chamberlain
  url:               https://twitter.com/recology_
  email:             myrmecocystus@gmail.com
